In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
xls = pd.ExcelFile('/content/drive/MyDrive/Data Viz/Project/FoodDesertLocatorData2006.xlsx')
df_2006 = pd.read_excel(xls, 'Cleaned_2016')
df_2006.loc[:,['Year', 'State', 'County', 'Urban', 'Pop2010', 'OHU2010', 'lapop1', 'lalowi1', 'laskids1', 'laseniors1', 'lahunv1']]

,Year,State,County,Urban,Pop2010,OHU2010,lapop1,lalowi1,laskids1,laseniors1,lahunv1
0,2016,AL,Autauga,Yes,1892,685.714286,43.9,10.0,14.0,4.7,3.5
1,2016,AL,Autauga,No,2982,1136.363636,59.2,12.7,16.8,7.0,6.6
2,2016,AL,Baldwin,Yes,3724,1291.666667,44.2,10.3,14.8,4.5,4.8
3,2016,AL,Barbour,No,4342,1217.391304,11.9,2.7,3.7,2.0,2.3
4,2016,AL,Barbour,No,4068,1172.413793,28.2,9.5,6.9,4.7,5.8
...,...,...,...,...,...,...,...,...,...,...,...
6524,2016,WY,Goshen,No,2900,1250.000000,59.4,10.7,15.0,7.9,0.4
6525,2016,WY,Laramie,Yes,3810,1604.651163,82.3,13.1,22.8,8.4,8.6
6526,2016,WY,Laramie,Yes,4440,583.333333,61.5,1.5,14.2,0.0,1.2
6527,2016,WY,Natrona,Yes,3692,1786.885246,70.3,21.6,17.1,13.0,12.2
6528,2016,WY,Niobrara,No,2407,1000.000000,24.2,3.7,5.5,4.1,0.8

In [ ]:
df_2019 = pd.read_csv('/content/drive/MyDrive/Data Viz/Project/FoodAccessResearchAtlasData2019 - Food Access Research Atlas.csv', index_col=0)
df_2019 = df_2019.reset_index()
df_2019.rename(columns = {"lakids1": "laskids1"})
df_2019 = df_2019.rename(columns = {"lakids1": "laskids1"})

In [ ]:
df_2019.columns

Index(['State', 'County', 'Urban', 'Pop2010', 'OHU2010', 'PovertyRate',
       'MedianFamilyIncome', 'lapophalf', 'lalowihalf', 'lakidshalf',
       'laseniorshalf', 'lawhitehalf', 'lablackhalf', 'laasianhalf',
       'lanhopihalf', 'laaianhalf', 'laomultirhalf', 'lahisphalf',
       'lahunvhalf', 'lasnaphalf', 'lapop1', 'lalowi1', 'lakids1',
       'laseniors1', 'lawhite1', 'lablack1', 'laasian1', 'lanhopi1', 'laaian1',
       'laomultir1', 'lahisp1', 'lahunv1', 'TractLOWI', 'TractKids',
       'TractSeniors', 'TractWhite', 'TractBlack', 'TractAsian', 'TractNHOPI',
       'TractAIAN', 'TractOMultir', 'TractHispanic'],
      dtype='object')

In [ ]:
df_2006.lapop1 = df_2006.lapop1*df_2006.Pop2010/100

In [ ]:
df_2006

,Year,State,County,Urban,Pop2010,OHU2010,PovertyRate,MedianFamilyIncome,lapophalf,lalowihalf,...,TractLOWI,TractKids,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic
0,2016,AL,Autauga,Yes,1892,685.714286,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016,AL,Autauga,No,2982,1136.363636,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2016,AL,Baldwin,Yes,3724,1291.666667,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2016,AL,Barbour,No,4342,1217.391304,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2016,AL,Barbour,No,4068,1172.413793,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6524,2016,WY,Goshen,No,2900,1250.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6525,2016,WY,Laramie,Yes,3810,1604.651163,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6526,2016,WY,Laramie,Yes,4440,583.333333,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6527,2016,WY,Natrona,Yes,3692,1786.885246,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6528,2016,WY,Niobrara,No,2407,1000.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Converting percentages to values
df_2006.lalowi1 = df_2006.lalowi1*df_2006.Pop2010/100
df_2006.laskids1 = df_2006.laskids1*df_2006.Pop2010/100
df_2006.laseniors1 = df_2006.laseniors1*df_2006.Pop2010/100
df_2006.lahunv1 = df_2006.lahunv1*df_2006.Pop2010/100
df_2006.loc[:,['Year', 'State', 'County', 'Urban', 'Pop2010', 'OHU2010', 'lapop1', 'lalowi1', 'laskids1', 'laseniors1', 'lahunv1']]

,Year,State,County,Urban,Pop2010,OHU2010,lapop1,lalowi1,laskids1,laseniors1,lahunv1
0,2016,AL,Autauga,Yes,1892,685.714286,830.588,189.200,264.880,88.924,66.220
1,2016,AL,Autauga,No,2982,1136.363636,1765.344,378.714,500.976,208.740,196.812
2,2016,AL,Baldwin,Yes,3724,1291.666667,1646.008,383.572,551.152,167.580,178.752
3,2016,AL,Barbour,No,4342,1217.391304,516.698,117.234,160.654,86.840,99.866
4,2016,AL,Barbour,No,4068,1172.413793,1147.176,386.460,280.692,191.196,235.944
...,...,...,...,...,...,...,...,...,...,...,...
6524,2016,WY,Goshen,No,2900,1250.000000,1722.600,310.300,435.000,229.100,11.600
6525,2016,WY,Laramie,Yes,3810,1604.651163,3135.630,499.110,868.680,320.040,327.660
6526,2016,WY,Laramie,Yes,4440,583.333333,2730.600,66.600,630.480,0.000,53.280
6527,2016,WY,Natrona,Yes,3692,1786.885246,2595.476,797.472,631.332,479.960,450.424
6528,2016,WY,Niobrara,No,2407,1000.000000,582.494,89.059,132.385,98.687,19.256

In [ ]:
#ceiling the data to make it integer
import math
df_2006.lapop1 = df_2006.lapop1.apply(lambda x: math.ceil(x))
df_2006.lalowi1 = df_2006.lalowi1.apply(lambda x: math.ceil(x))
df_2006.laskids1 = df_2006.laskids1.apply(lambda x: math.ceil(x))
df_2006.laseniors1 = df_2006.laseniors1.apply(lambda x: math.ceil(x))
df_2006.lahunv1 = df_2006.lahunv1.apply(lambda x: math.ceil(x))
df_2006.loc[:,['Year', 'State', 'County', 'Urban', 'Pop2010', 'OHU2010', 'lapop1', 'lalowi1', 'laskids1', 'laseniors1', 'lahunv1']]

,Year,State,County,Urban,Pop2010,OHU2010,lapop1,lalowi1,laskids1,laseniors1,lahunv1
0,2016,AL,Autauga,Yes,1892,685.714286,831,190,265,89,67
1,2016,AL,Autauga,No,2982,1136.363636,1766,379,501,209,197
2,2016,AL,Baldwin,Yes,3724,1291.666667,1647,384,552,168,179
3,2016,AL,Barbour,No,4342,1217.391304,517,118,161,87,100
4,2016,AL,Barbour,No,4068,1172.413793,1148,387,281,192,236
...,...,...,...,...,...,...,...,...,...,...,...
6524,2016,WY,Goshen,No,2900,1250.000000,1723,311,435,230,12
6525,2016,WY,Laramie,Yes,3810,1604.651163,3136,500,869,321,328
6526,2016,WY,Laramie,Yes,4440,583.333333,2731,67,631,0,54
6527,2016,WY,Natrona,Yes,3692,1786.885246,2596,798,632,480,451
6528,2016,WY,Niobrara,No,2407,1000.000000,583,90,133,99,20

In [ ]:
df_2019.columns

Index(['Year', 'State', 'County', 'Urban', 'Pop2010', 'OHU2010', 'PovertyRate',
       'MedianFamilyIncome', 'lapophalf', 'lalowihalf', 'lakidshalf',
       'laseniorshalf', 'lawhitehalf', 'lablackhalf', 'laasianhalf',
       'lanhopihalf', 'laaianhalf', 'laomultirhalf', 'lahisphalf',
       'lahunvhalf', 'lasnaphalf', 'lapop1', 'lalowi1', 'lakids1',
       'laseniors1', 'lawhite1', 'lablack1', 'laasian1', 'lanhopi1', 'laaian1',
       'laomultir1', 'lahisp1', 'lahunv1', 'TractLOWI', 'TractKids',
       'TractSeniors', 'TractWhite', 'TractBlack', 'TractAsian', 'TractNHOPI',
       'TractAIAN', 'TractOMultir', 'TractHispanic'],
      dtype='object')

In [ ]:
df_2019.loc[:,['Year', 'State', 'County', 'Urban', 'Pop2010', 'OHU2010', 'lapop1', 'lalowi1', 'laskids1', 'laseniors1', 'lahunv1']]

,Year,State,County,Urban,Pop2010,OHU2010,lapop1,lalowi1,laskids1,laseniors1,lahunv1
0,2019,Alabama,Autauga County,1,4803,1881,13384.0,4800.0,3639.0,1628.0,219.0
1,2019,Alabama,Autauga County,0,25405,9226,24040.0,7268.0,6333.0,2762.0,614.0
2,2019,Alabama,Autauga County,0,3320,1306,3320.0,1718.0,750.0,493.0,271.0
3,2019,Alabama,Baldwin County,0,95717,37415,85156.0,23869.0,19840.0,13301.0,1050.0
4,2019,Alabama,Baldwin County,1,82744,34255,43481.0,13620.0,9876.0,7921.0,521.0
...,...,...,...,...,...,...,...,...,...,...,...
72470,2019,Wyoming,Washakie County,0,3326,1317,2714.0,675.0,716.0,472.0,34.0
72471,2019,Wyoming,Washakie County,1,2665,1154,NaN,NaN,NaN,NaN,NaN
72472,2019,Wyoming,Washakie County,1,2542,1021,155.0,44.0,30.0,34.0,3.0
72473,2019,Wyoming,Weston County,0,3314,1322,2283.0,687.0,394.0,321.0,13.0
72474,2019,Wyoming,Weston County,1,3894,1699,1376.0,384.0,341.0,197.0,9.0

In [ ]:
df_combined = pd.concat([df_2019.loc[:,['Year', 'State', 'County', 'Urban', 'Pop2010', 'OHU2010', 'lapop1', 'lalowi1', 'laskids1', 'laseniors1', 'lahunv1']], df_2006.loc[:,['Year', 'State', 'County', 'Urban', 'Pop2010', 'OHU2010', 'lapop1', 'lalowi1', 'laskids1', 'laseniors1', 'lahunv1']]])
df_combined.to_csv('2016_19_accessibility.csv')